name: Package for windows

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run build.py
        run: |
          python -m pip install poetry
          poetry install
          poetry run python build.py

      - name: Upload the artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
